### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by daqniel** [cmu-ci-lab/inverseTransportNetworks#2]
@igkiou @Brucect2 The readme and project website mention your pre-trained models as available, but I can't find where. Have they been taken down?

**Comment by Brucect2** [comment]
Hi @daqniel, here is the pre-trained model. https://www.dropbox.com/s/gro2st63x58ytle/ITNNetworks.zip?dl=0

**Comment by daqniel** [comment]
Thanks!

**Comment by stymbhrdwj** [comment]
The link no longer works. Can you please re-upload? Thanks.
