### ISSUE TITLE
why normalization is needed?

### ISSUE THREAD

**Issue by ligoudaner377** [cmu-ci-lab/inverseTransportNetworks#3]
Hi, great work, thank you for your contribution!

I'm kind of new to computer graphics, 
when I read your code, I found that you multiply the reconstructed images with a constant (28.2486) when computing the loss between the GT images.
https://github.com/cmu-ci-lab/inverseTransportNetworks/blob/4e7c04efe589f1c023287985d55ac33a1e6cb65c/learning/train.py#L160
I'm curious that why this normalization is needed?

than you!

**Comment by Brucect2** [comment]
Hi @ligoudaner377 ,
Thanks for mentioning.
This normalization is just a global normalization term based on the entire dataset (essentially the max value of the input dataset).

**Comment by ligoudaner377** [comment]
Thank you for your fast reply! @Brucect2 

I'm still a little bit confused about this normalization.
Do you mean that the range of tmp_imgs and gt_imgs are different, for instance:
the intensity of tmp_imgs belongs to [0.0, 1.0],
 and the intensity of gt_imgs belongs to [0.0, 28.2486].
after multiplying a constant (28.2486), two images have the same range.

If so, this sounds a little weird to me.
Because both gt_imgs and tmp_imgs are rendered by mitsuba. The average intensity should be similar as the scene file are almost the same (the only difference is the scattering parameter).

I'm not sure if my understanding is correct or not...

**Comment by Brucect2** [comment]
Hi @ligoudaner377 ,
Sorry for the confusion. I preprocessed the dataset(gt) with the normalization term 28.2486 before feed everything into the network. That's why when I get the rendering from mitusbaAD during training, I scale it to the same range as my gt img.

**Comment by ligoudaner377** [comment]
Thanks for your reply! 
All my questions are cleared!
