### ISSUE TITLE
What is this mask?

### ISSUE THREAD

**Issue by ligoudaner377** [cmu-ci-lab/inverseTransportNetworks#4]
Hi! It's me again.

I found that you multiply a "mask" with the luminance image during the evaluation.
https://github.com/cmu-ci-lab/inverseTransportNetworks/blob/4e7c04efe589f1c023287985d55ac33a1e6cb65c/learning/eval.py#L90
Is this a binary mask that separates the foreground and background? I can not find this in your original paper.

Also, I noticed that during the training, It seems that this kind of preprocessing is not applied to the luminance image.
https://github.com/cmu-ci-lab/inverseTransportNetworks/blob/master/learning/train.py
Are there any special reasons that the "mask" is only needed during the evaluation?

would be grateful for your reply!

**Comment by Brucect2** [comment]
Hi @ligoudaner377,
Thanks for pointing out. This binary mask separates the foreground and background. In the training set I did apply the mask beforehand but I uploaded the data with background. I will upload the mask for each shape very soon.
