### ISSUE TITLE
 Function "extract_patches" has been deprecated

### ISSUE THREAD

**Issue by ligoudaner377** [cmu-ci-lab/inverseTransportNetworks#5]
Hi, it's me again.
Sorry for bothering you so many times. 

https://github.com/cmu-ci-lab/inverseTransportNetworks/blob/4e7c04efe589f1c023287985d55ac33a1e6cb65c/learning/eval.py#L25

This function has been deprecated in the current sklearn package, and I couldn't find any document about this.

https://github.com/cmu-ci-lab/inverseTransportNetworks/blob/4e7c04efe589f1c023287985d55ac33a1e6cb65c/learning/eval.py#L100
If my understanding was correct, the purpose of using this function here is to resize the image from 512x512 to 128x128.
I want to ask if I can just use some linear interpolation technics to resize the image?

**Comment by Brucect2** [comment]
Hi @ligoudaner377 
No worries. Yes something like an average pooling or linear interpolation should have similar effects.
